# Generated by Django 6.0.6 on 2026-07-15 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0007_documento_tipo_presentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaNoHabil',
            fields=[
                ('id_fecha_no_habil', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='Fecha no hábil', unique=True)),
                ('descripcion', models.CharField(help_text='Descripción de la fecha (ej: Feriado por Año Nuevo)', max_length=200)),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado nacional'), ('DESCANSO_PEDAGOGICO', 'Descanso pedagógico'), ('SUSPENSION', 'Suspensión de actividades'), ('OTRO', 'Otro')], default='FERIADO', max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechas_no_habiles_creadas', to='tribunal.usuario')),
            ],
            options={
                'db_table': 'fecha_no_habil',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='DenunciadoDenuncia',
            fields=[
                ('id_denunciado_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_denunciado', models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('DOCENTE', 'Docente'), ('ADMINISTRATIVO', 'Administrativo'), ('AUTORIDAD', 'Autoridad')], default='ESTUDIANTE', max_length=20)),
                ('es_principal', models.BooleanField(default=False, help_text='Indica si es el denunciado principal (usado para notificaciones y resoluciones)')),
                ('fecha_inclusion', models.DateField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denunciados_adicionales', to='tribunal.denuncia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_como_denunciado', to='tribunal.persona')),
            ],
            options={
                'db_table': 'denunciado_denuncia',
                'unique_together': {('denuncia', 'persona')},
            },
        ),
        migrations.CreateModel(
            name='DenuncianteDenuncia',
            fields=[
                ('id_denunciante_denuncia', models.AutoField(primary_key=True, serialize=False)),
                ('es_principal', models.BooleanField(default=False, help_text='Indica si es el denunciante principal (usado para notificaciones)')),
                ('fecha_inclusion', models.DateField(auto_now_add=True)),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denunciantes_adicionales', to='tribunal.denuncia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='denuncias_como_denunciante', to='tribunal.persona')),
            ],
            options={
                'db_table': 'denunciante_denuncia',
                'unique_together': {('denuncia', 'persona')},
            },
        ),
    ]
