# Generated by Django 6.0.6 on 2026-07-15 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0008_add_partes_denuncia_y_calendario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechanohabil',
            options={'ordering': ['fecha_inicio']},
        ),
        migrations.RemoveField(
            model_name='fechanohabil',
            name='fecha',
        ),
        migrations.AddField(
            model_name='fechanohabil',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fechanohabil',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Último día (inclusive). Igual a fecha_inicio si es un solo día.', null=True),
        ),
        migrations.AddField(
            model_name='fechanohabil',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2026, 7, 15), help_text='Primer día del período inhábil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fechanohabil',
            name='descripcion',
            field=models.CharField(help_text='Descripción breve del motivo', max_length=200),
        ),
        migrations.AlterField(
            model_name='fechanohabil',
            name='tipo',
            field=models.CharField(choices=[('FERIADO', 'Feriado nacional'), ('RECESO', 'Receso universitario'), ('SIN_AUDIENCIA', 'Sin audiencias'), ('SUSPENSION', 'Suspensión de actividades'), ('OTRO', 'Otro')], default='FERIADO', max_length=30),
        ),
    ]
